### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by nicholasalanbrown** [Differential/meteor-blog#149]
Hello:

Maybe I'm just misunderstanding how it works, but upon clicking the "plus" icon in the post body to add an image, both the image and code buttons do nothing upon clicking. How is image upload supposed to work? Is there a dependent package I need to add?

Thanks!

**Comment by hellogerard** [comment]
Which release/revision are you using?  The last release shouldn't even have the "code" icon in the "plus" popup, though `master` does.

**Comment by coopermaruyama** [comment]
@nicholasalanbrown , on `master` that was caused by some events getting bound too many times which would freeze them up. #142 should fix this and will be merged in soon.

**Comment by nicholasalanbrown** [comment]
I'm just pulling from the ```master``` branch of the GIthub repo - I don't see any other branches to pull from other than ```gh-pages```

**Comment by coopermaruyama** [comment]
The releases are [here](https://github.com/Differential/meteor-blog/releases) and you can specify it by using `meteor add ryw:blog@x.x.x`. Also here's a branch from my fork that you can use as well https://github.com/coopermaruyama/meteor-blog/tree/f2bd0a14cb4a0564c8166f8e9761ae3a6291f0bf

**Comment by nicholasalanbrown** [comment]
Thanks for the guidance! Since the latest release in the link you shared
was from August, I cloned your branch instead:

1. When editing a plus and clicking the "+" sign, I'm presented with just
the image option but clicking it does nothing.

2. If I instead try and drag a picture and drop it into the post, it works
reasonably well except that it drops in one normal scaled picture and a
handful of skewed copies of it. See the attached screenshot. Any idea?

**Comment by nicholasalanbrown** [comment]
I'm pretty confused. I keep cloning master, add the package locally, and
not seeing the fixes you're mentioning. I still see the notifications
refreshing constantly, as well as the aforementioned image issue.

**Comment by coopermaruyama** [comment]
Ah, in order to add a local package you need to set an environment variable `PACKAGE_DIRS` to whatever directory contains your local packages. Assuming you keep your apps at `~/sites/` and your packages at `~/sites/packages/`, do the following:

```
echo "export PACKAGE_DIRS=$HOME/meteor/packages" >> ~/.bashrc;
. ~/.bashrc
```

Alternatively, you can also run `mrt link-package /path/to/package` from your app's root to link individual packages.

Just to be safe I would also remove the version constraint (`author:package` instead of `author:package@x.x.x`) as I'm pretty sure your app won't use the local version if the version doesn't match exactly.

Let me know if this works.

**Comment by hellogerard** [comment]
@nicholasalanbrown,

Can you try running the _latest_ `master` from this package? I've merged all outstanding PRs. It's  working for me. URL embeds are turned off for now.

BTW, the `releases` page is out of date as the tags are out of date. But I will be tagging releases from now on.

**Comment by hellogerard** [comment]
@nicholasalanbrown, BTW, if this fixes this issue and #148, I'll publish a new release.

**Comment by nicholasalanbrown** [comment]
Hmm, I'll try the "adding a local package" tip Cooper suggested (though I
recall having done this before at some point), but I've typically been
cloning master (I assume always the freshest code) into a /packages
directory, editing the package.js file to change the package name to
something like "myproject:blog" so as not to confuse Meteor, then running
"meteor add myproject:blog" so as to be sure I'm referencing the local
package. When I do that, I still don't see the aforementioned fixes (i.e.
the duplicated images, the refreshing notifications). I think Meteor
already knows where to find any local packages (i.e. in "/packages") since
I must have already set up that link with mrt.

Let me know if I'm misunderstanding something here.

**Comment by hellogerard** [comment]
Hmm. Here's what I do.

1. Add the pkg like normal with `meteor add ryw:blog`. 
2. Then create a `packages` folder in your project. 
3. Clone the repo into that folder with a name of ryw:blog.

There's no `package.js` file, unless you're working on your own package that depends on blog.

**Comment by nicholasalanbrown** [comment]
Great, I think I've got all of this working. Thanks!
